apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-istioctl
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - "create"
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - serviceaccounts
  verbs:
  - list
  - get
  - create
  - update
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list 
  - create
  - update
- apiGroups:
  - "apps"
  resources:
  - daemonsets
  - replicasets
  verbs:
  - list
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - list
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
- apiGroups:
  - "rbac.authorization.k8s.io"
  resources:
  - rolebindings
  - roles
  - clusterroles
  - clusterrolebindings
  verbs:
  - "*"
- apiGroups:
  - "admissionregistration.k8s.io"
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - patch 
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
- apiGroups:
  - "apiextensions.k8s.io"
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - "networking.istio.io"
  resources:
  - destinationrules
  - envoyfilters
  - gateways
  - virtualservices
  verbs:
  - list
- apiGroups:
  - "security.istio.io"
  resources:
  - peerauthentications
  verbs:
  - list