apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-istioctl
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - namespaces
  - nodes
  - pods
  - secrets
  - services
  - clusterrolebinding
  - clusterrole
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resourceNames:
  - istio
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  resources:
  - '*'
  verbs:
  - list